### ISSUE TITLE
问题三交点报错

### ISSUE THREAD

**Issue by kaka1453** [doctorzu/2024-C-#1]
(myenv@3.9) (base) boa@MacBook-Air GitHub众 % /Users/boa/miniconda3/envs/myenv@3.9/bin/python /Users/boa/Documents/MCM_ICM_2024_Resource/GitHub众/2024-C-/code/问题3交点.py
Traceback (most recent call last):
  File "/Users/boa/Documents/MCM_ICM_2024_Resource/GitHub众/2024-C-/code/问题3交点.py", line 30, in <module>
    combined_train_df, combined_test_df = dataset_split(dataframes, ratio=0.2)
  File "/Users/boa/Documents/MCM_ICM_2024_Resource/GitHub众/2024-C-/code/问题3交点.py", line 25, in dataset_split
    combined_train_df = pd.concat(train_dfs, ignore_index=True)
  File "/Users/boa/miniconda3/envs/myenv@3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Users/boa/miniconda3/envs/myenv@3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Users/boa/miniconda3/envs/myenv@3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by doctorzu** [comment]
您好，这是我们中间的过程文件。你们也在做这道题吗？方便交流一下吗？

**Comment by kaka1453** [comment]
您好，我的qq是3395813040，欢迎交流
